CREATE SEQUENCE TARJETAS_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE USUARIOS_SEQ
INCREMENT BY 1
START WITH 1;



SELECT TARJETAS_SEQ.CURRVAL AS VALOR_ACTUAL
FROM DUAL;

SELECT USUARIOS_REGISTRADOS_SEQ.CURRVAL AS VALOR_ACTUAL2
FROM DUAL;




--PROCEDIMIENTO PARA INGRESAR TARGETAS DE REGALO EN CADA USUARIO
CREATE OR REPLACE PROCEDURE P_AGREGAR_TARJETA (
            P_CODIGO_LUGAR IN INTEGER,
            P_CODIGO_USUARIO IN INTEGER,
            P_FECHA_CANJEA IN DATE,
            P_CODIGO_A_CANJEAR IN NUMBER,
            P_CODIGO_TARJETA_REGALO out integer
)AS
BEGIN
    P_CODIGO_TARJETA_REGALO:=TARJETAS_SEQ.NEXTVAL;
    INSERT INTO TBL_TARJETA_REGALO (
        CODIGO_TARJETA_REGALO,
        CODIGO_LUGAR,
        CODIGO_USUARIO,
        FECHA_CAJEA,
        CODIGO_A_CAJEAR
    ) VALUES (
        P_CODIGO_TARJETA_REGALO,
        P_CODIGO_LUGAR,
        P_CODIGO_USUARIO,
        P_FECHA_CANJEA,
        P_CODIGO_A_CANJEAR
    );
END;

SET SERVEROUTPUT ON;

DECLARE
    V_CODIGO_TARJETA_REGALO INTEGER;
BEGIN
    P_AGREGAR_TARJETA (7, 7, TO_DATE('12-05-2016', 'DD-MM-YYYY'), 123456789524, V_CODIGO_TARJETA_REGALO);
    DBMS_OUTPUT.PUT_LINE('CODIGO_TARJETA_AGREGADA: '||V_CODIGO_TARJETA_REGALO);
END;




--PROCEDIMIENTO PARA INGRESAR USUARIOS DE MODULO DE REGISTRO

CREATE OR REPLACE PROCEDURE P_AGREGAR_NUEVO_USUARIO (
            P_CODIGO_GENERO IN INTEGER,
            P_CODIGO_LUGAR_VIVE IN INTEGER,
            P_CODIGO_MARCA_TELEFONO_M IN INTEGER,
            P_CODIGO_PROVEEDOR_SERVICIO IN INTEGER,
            P_CODIGO_TIPO_USUARIO IN INTEGER,
            P_CODIGO_PLANES_CUENTA IN INTEGER,
            P_NOMBRE_COMPLETO IN VARCHAR2,
            P_FECHA_NACIMIENTO IN DATE,
            P_USUARIO_PLATAFORMA IN VARCHAR2,
            P_CORREO_ELECTRONICO IN VARCHAR2,
            P_CONTRASENA IN VARCHAR2,
            P_NUMERO_TELEFONO IN NUMBER,
            P_CODIGO_USUARIO out integer
)AS
BEGIN
    P_CODIGO_USUARIO:=USUARIOS_REGISTRADOS_SEQ.NEXTVAL;
    INSERT INTO TBL_USUARIOS (
        CODIGO_USUARIO,
        CODIGO_GENERO,
        CODIGO_LUGAR_VIVE,
        CODIGO_MARCA_TELEFONO_M,
        CODIGO_PROVEEDOR_SERVICIO,
        CODIGO_TIPO_USUARIO,
        CODIGO_PLANES_CUENTA,
        NOMBRE_COMPLETO,
        FECHA_NACIMIENTO,
        USUARIO_PLATAFORMA,
        CORREO_ELECTRONICO,
        CONTRASENA,
        NUMERO_TELEFONO
    ) VALUES (
        P_CODIGO_USUARIO,
        P_CODIGO_GENERO,
        P_CODIGO_LUGAR_VIVE,
        P_CODIGO_MARCA_TELEFONO_M,
        P_CODIGO_PROVEEDOR_SERVICIO,
        P_CODIGO_TIPO_USUARIO,
        P_CODIGO_PLANES_CUENTA,
        P_NOMBRE_COMPLETO,
        P_FECHA_NACIMIENTO,
        P_USUARIO_PLATAFORMA,
        P_CORREO_ELECTRONICO,
        P_CONTRASENA,
        P_NUMERO_TELEFONO
    );
END;

SET SERVEROUTPUT ON;

DECLARE
    V_CODIGO_USUARIO INTEGER;
BEGIN
    P_AGREGAR_NUEVO_USUARIO (2, 8, 4, 2, 1, 1, 'Alonzo Carbajal Moreno', TO_DATE('12-05-1970', 'DD-MM-YYYY'), 'alonzo1', 'alonzo1@gmail.com', 'asd.456', 89562341, V_CODIGO_USUARIO);
    DBMS_OUTPUT.PUT_LINE('CODIGO_USUARIO_AGREGADO: '||V_CODIGO_USUARIO);
END;