CREATE SEQUENCE TARJETAS_SEQ
INCREMENT BY 1
START WITH 1;


CREATE SEQUENCE USUARIOS_SEQ
INCREMENT BY 1
START WITH 1;



SELECT TARJETAS_SEQ.CURRVAL AS VALOR_ACTUAL
FROM DUAL;

SELECT USUARIOS_REGISTRADOS_SEQ.CURRVAL AS VALOR_ACTUAL2
FROM DUAL;




--PROCEDIMIENTO PARA INGRESAR TARGETAS DE REGALO EN CADA USUARIO
CREATE OR REPLACE PROCEDURE P_AGREGAR_TARJETA (
            P_CODIGO_LUGAR IN INTEGER,
            P_CODIGO_USUARIO IN INTEGER,
            P_FECHA_CANJEA IN DATE,
            P_CODIGO_A_CANJEAR IN NUMBER,
            P_CODIGO_TARJETA_REGALO out integer
)AS
BEGIN
    P_CODIGO_TARJETA_REGALO:=TARJETAS_SEQ.NEXTVAL;
    INSERT INTO TBL_TARJETA_REGALO (
        CODIGO_TARJETA_REGALO,
        CODIGO_LUGAR,
        CODIGO_USUARIO,
        FECHA_CAJEA,
        CODIGO_A_CAJEAR
    ) VALUES (
        P_CODIGO_TARJETA_REGALO,
        P_CODIGO_LUGAR,
        P_CODIGO_USUARIO,
        P_FECHA_CANJEA,
        P_CODIGO_A_CANJEAR
    );
END;

SET SERVEROUTPUT ON;

DECLARE
    V_CODIGO_TARJETA_REGALO INTEGER;
BEGIN
    P_AGREGAR_TARJETA (7, 7, TO_DATE('12-05-2016', 'DD-MM-YYYY'), 123456789524, V_CODIGO_TARJETA_REGALO);
    DBMS_OUTPUT.PUT_LINE('CODIGO_TARJETA_AGREGADA: '||V_CODIGO_TARJETA_REGALO);
END;

